*** Settings ***

*** Variables ***
${platform_txt_forgot_password_title}                
${platform_txt_forgot_password_sub_title}       
${platform_txt_forgot_password_email_title}     
${platform_input_forgot_password_email}         
${platform_txt_forgot_password_phone_title}     
${platform_input_forgot_password_phone}         
${platform_btn_forgot_password_continue}        
${platform_btn_forgot_password_back}            
${platform_txt_forgot_password_email_error}     
