*** Settings ***

*** Variables ***
${platform_txt_signup_verify_otp_time}               
${platform_input_signup_verify_otp_otp}              
${platform_linktxt_signup_verify_otp_resend}         
${platform_txt_signup_verify_otp_resend}             
${platform_txt_signup_verify_otp_title}              
${platform_txt_signup_verify_otp_mobile_subtitle}    
${platform_txt_signup_verify_otp_email_subtitle}     
${platform_txt_signup_verify_otp_incorrect}          
${platform_txt_signup_verify_otp_expired}            
${platform_txt_signup_verify_otp_reached_limit}      
