*** Variables ***
&{USER_INVALID_ACCOUNT}     cust_code=111111   email=pi21.invalid.acc@gmail.com  password=WrongP@ssword    mobile_number=0615678540
&{USER_GUEST_ACCOUNT}       cust_code=         email=pi21.guest.acc@gmail.com    password=Pi123456!    mobile_number=0800001000
&{USER_SET_ACCOUNT}         cust_code=0800487  email=pi6059@test.com             password=P@ssw0rd     mobile_number=0932440564
&{USER_TRADE_ACCOUNT}       cust_code=0800165  email=qa1511_1@test.com           password=P@ssw0rd     mobile_number=        pin_code=159357
&{USER_FORGOT_ACCOUNT}      cust_code=         email=pi21.forgot.acc@gmail.com   password=Pi123456!    mobile_number=0800002000

